export const fullInvoiceTableKeys: string[] = [
	"typeOfInvoice",
	"series",
	"number",
	"date",
	"numberOfAccompanyingNotice",
	"isCancelled",
	"cancellationNotices",
	"borderColor",
	"paymentStatus",
	"buyer.name",
	"totalCost",
	"totalPayments",
	"addedBy",
	"editedBy",
];
