export const environment = {
  production: true,
  baseUrl: 'https://easy-invoice-simple.herokuapp.com/api/',
  pageSizeOptions: [10, 25, 50, 100],
  contractModels: {
    acceptedFields: [
      '{nume-furnizor}',
      '{j-furnizor}',
      '{cui-furnizor}',
      '{sediu-furnizor}',
      '{judet-furnizor}',
      '{cont-bancar-furnizor}',
      '{banca-furnizor}',
      '{email-furnizor}',
      '{telefon-furnizor}',
      '{nume-client}',
      '{delegat-furnizor}',
      '{j/serie-client}',
      '{cui/cnp-client}',
      '{sediu-client}',
      '{judet-client}',
      '{cont-bancar-client}',
      '{banca-client}',
      '{email-client}',
      '{telefon-client}',
      '{numar-contract}',
      '{data-contract}',
      '{obiect-contract}',
      '{produse-contract}',
      '{valoare-contract}',
      '{avans-contract}',
      '{rest-plata-contract}',
      '{metoda-plata-contract}',
      '{transport-contract}',
      '{montaj-contract}',
      '{termen-livrare-contract}',
    ],
    mandatoryFields: [
      '{nume-furnizor}',
      '{j-furnizor}',
      '{cui-furnizor}',
      '{sediu-furnizor}',
      '{judet-furnizor}',
      '{nume-client}',
      '{j/serie-client}',
      '{cui/cnp-client}',
      '{sediu-client}',
      '{judet-client}',
      '{numar-contract}',
      '{data-contract}',
      '{obiect-contract}',
    ],
  },
};
